### ISSUE TITLE
Support for properties dict while retaining comments?

### ISSUE THREAD

**Issue by dimaspivak** [jwodder/javaproperties#1]
Hey there,

I've been looking for a full-featured library to handle Java properties and your implementation looks to be the most thorough on the internet, so +1 for that. :) My use case is that I want to be able to load a `.properties` file, change just a handful of lines, and then serialize it back to a file (while retaining comments, blank lines, etc.). I've discovered the low-level `parse` method which returns a generator of tuples, but is there an in-built way to create an object from a `.properties` file which has k-v lookup/modification along with the ability to serialize back to a file with comments? 

If not, would you be open to a PR to add such support? I'd be happy to do it if you could give me guidance on how you'd prefer the design to look.

**Comment by jwodder** [comment]
Bad news: I started thinking about the design of such a class and accidentally thought so hard that I wrote the whole thing; [is this the sort of thing you had in mind?](http://javaproperties.readthedocs.io/en/latest/propfile.html)

**Comment by dimaspivak** [comment]
Dang, John. [We're not worthy.](https://media.giphy.com/media/iiS84hOJXh1Pq/giphy.gif) This is perfect! Thank you so much.
