### ISSUE TITLE
PropertiesFile ensure_ascii

### ISSUE THREAD

**Issue by bhack** [jwodder/javaproperties#12]
Can we pass `ensure_ascii` in 
https://github.com/jwodder/javaproperties/blob/9dab5b5c0abdfb54037e4743dbaf5d261809c2bc/src/javaproperties/propfile.py#L239

**Comment by jwodder** [comment]
`PropertiesFile.dump()` and `PropertiesFile.dumps()` now take an `ensure_ascii` argument.  This new version will be released in a day or two, as soon as I add type annotations to the library.
