### ISSUE TITLE
ensure_ascii

### ISSUE THREAD

**Issue by adriangalera** [jwodder/javaproperties#7]
I have been using this library recently and I'm really missing the feature to print non-ascii tests.

I know json library provide the option `ensure_ascii` to allow unicode characters.

Could you consider adding this option to the library?

I've found that if I use dump_xml or load_xml it works by playing around with encoding. So, please could you add the encoding option to dump or load ?

Thanks!

Example:

```python
import javaproperties
a = {"key":"valòr"}
javaproperties.dumps(a)
```
output: 
```
#Tue Feb 18 15:43:21 CET 2020
key=val\\u00f2r
```
Expected output:
```
#Tue Feb 18 15:43:21 CET 2020
key=valòr
```

**Comment by jwodder** [comment]
I have added support for an `ensure_ascii` parameter (default value `True`) to the `dump()` and `dumps()` functions.  This new feature is available in version 0.6.0, released moments ago.
